version: '3'
services: 
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - 80:80
      - 443:443
    volumes: 
      - /ect/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from: nginx-proxy
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh
    environment: 
      - DEFAULT_EMAIL=mail@elementec.de
